version: '3'

services:
  traefik:
    image: traefik:latest
    ports:
      # The HTTP port
      - "80:80"
      - "443:443"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    networks:
      - traefik  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
      - ./dynamic-conf.toml:/etc/traefik/dynamic-conf.toml
      - ./logs:/data/logs
      - ./ssl:/etc/ssl
      
networks:
  traefik:
    external: true      