## Dynamic configuration
[http.routers.traefik-https]
  rule = "Host(`traefik.space.xyz`)"
  entryPoints = ["https"]
  service = "api@internal"
  middlewares = ["auth"]
  [http.routers.traefik-https.tls]

# 用户：test 密码：test
[http.middlewares.auth.basicAuth]
  users = [
    "test:$apr1$H6uskkkW$IgXLP6ewTrSuBkTrqE8wj/",
  ]

[tls]
  [[tls.certificates]]
    certFile = "/etc/ssl/javachen.xyz.cer"
    keyFile = "/etc/ssl/javachen.xyz.key"
  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/etc/ssl/javachen.xyz.cer"
        keyFile = "/etc/ssl/javachen.xyz.key"