version: '3'
services:
  reverse-proxy:
    image: traefik:latest
    command:
    - --api
    - --api.insecure
    - --providers.docker
    - --entrypoints.mysql.address=:3306
    ports:
      - "3306:3306"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mysql:
    image: mysql:5.7
    labels:
      - "traefik.tcp.routers.mysql.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.mysql.entrypoints=mysql"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: 123456
      TZ: Asia/Shanghai