apiVersion: v1
kind: ReplicationController            
metadata:
  name: mysql                          
spec:
  replicas: 1                          
  selector:
    app: mysql                          
  template:
    metadata:
      labels:
        app: mysql                      
    spec:
      containers:                       
      - name: mysql                     
        image: mysql:5.7                
        ports:
        - containerPort: 3306           
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        - name: MYSQL_DATABASE
          value: sonardb
        - name: MYSQL_USER
          value: sonar
        - name: MYSQL_PASSWORD
          value: sonar