version: '3'
services:
  pebble:
    image: letsencrypt/pebble:latest
    command: pebble -config /test/config/pebble-config.json -strict -dnsserver 10.30.50.1:5053
    environment:
      # TODO(@cpu): Delete this explicit GODEBUG env var once Pebble is built
      # with Go 1.13.x which defaults TLS 1.3 to on
      GODEBUG: "tls13=1"
      PEBBLE_VA_NOSLEEP: 1
    ports:
      - 14000:14000  # HTTPS ACME API
      - 15000:15000  # HTTPS Management API
    volumes:
      - /etc/hosts:/etc/hosts
      - ./pebble.config:/test/config/pebble-config.json
    links:
      - dns
    networks:
      acmenet:

  dns:
    build: ./dns
    ports:
      - "5053:5053/udp"
    networks:
      acmenet:

networks:
  acmenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.50.0/24
