---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: 'traefik'
spec:
  rules:
  - host: grafana.platform9.traefikee-demo.containous.cloud
    http:
      paths:
      - backend:
          serviceName: grafana
          servicePort: 3000