version: '3'
services:
  reverseproxy:
    image: traefik:v2.0
    command:
      - --configfile=/traefik.yml
      - --log.level=DEBUG
      - --api.insecure=true
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml
    networks:
      ossnet:

  demo1:
    image: juliens/webapp
    environment:
      - APPNAME=DEMO1
    networks:
      ossnet:

  demo2:
    image: juliens/webapp
    environment:
      - APPNAME=DEMO2
    labels:
      - traefik.http.routers.demo2.rule=Host(`myapp.com`)
    networks:
      ossnet:

  pebble:
    image: letsencrypt/pebble:latest
    command: pebble -config /test/config/pebble-config.json -strict -dnsserver 10.30.50.1:5053
    environment:
      # TODO(@cpu): Delete this explicit GODEBUG env var once Pebble is built
      # with Go 1.13.x which defaults TLS 1.3 to on
      GODEBUG: "tls13=1"
    ports:
      - 14000:14000  # HTTPS ACME API
      - 15000:15000  # HTTPS Management API
    volumes:
      - /etc/hosts:/etc/hosts
      - ./pebble.config:/test/config/pebble-config.json
    networks:
      ossnet:

  dns:
    build: ./dns
    ports:
      - "5053:5053"
    networks:
      ossnet:

networks:
  ossnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.30.50.0/24
