log:
    level: DEBUG

providers:
    docker: true

entrypoints:
    my-secure:
        address: ":443"

api:
    insecure: true

certificatesResolvers:
    myLE:
        acme:
            email: julien@containo.us
            caserver: https://pebble:14000/dir
            tlsChallenge: {}

