version: '3.4'
services:
  traefik:
    image: traefik:v2.0.0
    command: --global.debug --api --entryPoints='Name:http Address::80' --entryPoints='Name:https Address::443' --providers.docker.exposedByDefault=false
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080
      - 443:443
  server:
    image: rancher/k3s:v0.3.0
    command: server --disable-agent --no-deploy traefik --no-deploy coredns
    environment:
      - K3S_CLUSTER_SECRET=somethingtotallyrandom
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
    volumes:
      - ./images:/var/lib/rancher/k3s/agent/images
      # This is just so that we get the kubeconfig file out
      - /tmp/k3s-output:/output
    ports:
      - 6443:6443

  node:
    image: rancher/k3s:v0.3.0
    command: agent
    tmpfs:
      - /run
      - /var/run
    volumes:
      - ./images:/var/lib/rancher/k3s/agent/images
    privileged: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.http.rule=Method(`GET`,`POST`,`PUT`,`HEAD`,`DELETE`, `OPTIONS`)"
      - "traefik.http.routers.http.entrypoints=http"
      - "traefik.http.services.service1.loadbalancer.server.port=80"
      - "traefik.tcp.routers.https.rule=HostSNI(`whoami.docker.localhost`,`dashboard.docker.localhost`,`hotrod.docker.localhost`,`tracing.docker.localhost`, `webapp.docker.localhost`)"
      - "traefik.tcp.routers.https.tls.passthrough=true"
      - "traefik.tcp.routers.https.entrypoints=https"
      - "traefik.tcp.services.service1.loadbalancer.server.port=443"
    environment:
      - K3S_URL=https://server:6443
      - K3S_CLUSTER_SECRET=somethingtotallyrandom
